
admin = {
    checkbox = {},
    edit = {},
    window = {},
    tabpanel = {},
    radiobutton = {},
    button = {},
    label = {},
    tab = {},
    gridlist = {}
}
addEventHandler("onClientResourceStart", resourceRoot,
    function()
        admin.window[1] = guiCreateWindow(208, 59, 963, 616, "AuroraRPG - Admins Panel", false)
        guiWindowSetSizable(admin.window[1], false)
        guiSetAlpha(admin.window[1], 1.00)
		guiSetVisible(admin.window[1], false)

        admin.radiobutton[1] = guiCreateRadioButton(9, 29, 126, 26, "Active Mode", false, admin.window[1])
        guiSetFont(admin.radiobutton[1], "clear-normal")
        guiRadioButtonSetSelected(admin.radiobutton[1], true)
        admin.radiobutton[2] = guiCreateRadioButton(9, 55, 126, 26, "Offline Mode", false, admin.window[1])
        guiSetFont(admin.radiobutton[2], "clear-normal")
        admin.radiobutton[3] = guiCreateRadioButton(9, 81, 126, 26, "Ghost Admin", false, admin.window[1])
        guiSetFont(admin.radiobutton[3], "clear-normal")
        admin.label[1] = guiCreateLabel(15, 117, 110, 21, "Players", false, admin.window[1])
        guiSetFont(admin.label[1], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[1], "center")
        admin.gridlist[1] = guiCreateGridList(9, 142, 173, 464, false, admin.window[1])
        guiGridListAddColumn(admin.gridlist[1], "Players", 0.9)
        admin.tabpanel[1] = guiCreateTabPanel(187, 118, 766, 488, false, admin.window[1])

        admin.tab[1] = guiCreateTab("Info & Actions", admin.tabpanel[1])

        admin.label[2] = guiCreateLabel(8, 9, 378, 26, "________________________________________________", false, admin.tab[1])
        guiSetFont(admin.label[2], "clear-normal")
        guiLabelSetColor(admin.label[2], 241, 3, 250)
        guiLabelSetVerticalAlign(admin.label[2], "center")
        admin.label[3] = guiCreateLabel(8, 35, 378, 26, "Main Player Details", false, admin.tab[1])
        guiSetFont(admin.label[3], "clear-normal")
        guiLabelSetColor(admin.label[3], 17, 209, 237)
        guiLabelSetHorizontalAlign(admin.label[3], "center", false)
        guiLabelSetVerticalAlign(admin.label[3], "center")
        admin.label[4] = guiCreateLabel(8, 61, 378, 26, "Player Name: ", false, admin.tab[1])
        guiSetFont(admin.label[4], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[4], "center")
        admin.label[5] = guiCreateLabel(8, 87, 378, 26, "Player Account (ID): ", false, admin.tab[1])
        guiSetFont(admin.label[5], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[5], "center")
        admin.label[6] = guiCreateLabel(8, 113, 378, 26, "Player Serial (IP): ", false, admin.tab[1])
        guiSetFont(admin.label[6], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[6], "center")
        admin.label[7] = guiCreateLabel(8, 139, 378, 26, "Player Location:  ", false, admin.tab[1])
        guiSetFont(admin.label[7], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[7], "center")
        admin.label[8] = guiCreateLabel(8, 165, 378, 26, "Player Ping (FPS):   ", false, admin.tab[1])
        guiSetFont(admin.label[8], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[8], "center")
        admin.label[9] = guiCreateLabel(8, 191, 378, 26, "Player Using Mods:    ", false, admin.tab[1])
        guiSetFont(admin.label[9], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[9], "center")
        admin.label[10] = guiCreateLabel(8, 217, 378, 26, "________________________________________________", false, admin.tab[1])
        guiSetFont(admin.label[10], "clear-normal")
        guiLabelSetColor(admin.label[10], 241, 3, 250)
        guiLabelSetVerticalAlign(admin.label[10], "center")
        admin.label[11] = guiCreateLabel(8, 243, 378, 26, "Player In-game Deatils", false, admin.tab[1])
        guiSetFont(admin.label[11], "clear-normal")
        guiLabelSetColor(admin.label[11], 17, 209, 237)
        guiLabelSetHorizontalAlign(admin.label[11], "center", false)
        guiLabelSetVerticalAlign(admin.label[11], "center")
        admin.label[12] = guiCreateLabel(8, 269, 378, 26, "Player Team (Occupation):  ", false, admin.tab[1])
        guiSetFont(admin.label[12], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[12], "center")
        admin.label[13] = guiCreateLabel(8, 295, 378, 26, "Player Interior (Dim): ", false, admin.tab[1])
        guiSetFont(admin.label[13], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[13], "center")
        admin.button[1] = guiCreateButton(312, 201, 66, 26, "Copy", false, admin.tab[1])
        guiSetFont(admin.button[1], "default-bold-small")
        guiSetProperty(admin.button[1], "NormalTextColour", "FFAAAAAA")
        admin.label[14] = guiCreateLabel(8, 321, 378, 26, "Player Hours (Score): ", false, admin.tab[1])
        guiSetFont(admin.label[14], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[14], "center")
        admin.label[15] = guiCreateLabel(8, 347, 378, 26, "Player HP (Armor):  ", false, admin.tab[1])
        guiSetFont(admin.label[15], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[15], "center")
        admin.label[16] = guiCreateLabel(8, 373, 378, 26, "Player Money (Bank):   ", false, admin.tab[1])
        guiSetFont(admin.label[16], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[16], "center")
        admin.label[17] = guiCreateLabel(8, 399, 378, 26, "Player Group:    ", false, admin.tab[1])
        guiSetFont(admin.label[17], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[17], "center")
        admin.label[18] = guiCreateLabel(8, 425, 378, 26, "Player Vehicle (HP):     ", false, admin.tab[1])
        guiSetFont(admin.label[18], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[18], "center")
        admin.button[2] = guiCreateButton(315, 425, 66, 26, "Copy", false, admin.tab[1])
        guiSetFont(admin.button[2], "default-bold-small")
        guiSetProperty(admin.button[2], "NormalTextColour", "FFAAAAAA")
        admin.label[19] = guiCreateLabel(388, 9, 378, 26, "______________________________________________", false, admin.tab[1])
        guiSetFont(admin.label[19], "clear-normal")
        guiLabelSetColor(admin.label[19], 241, 3, 250)
        guiLabelSetVerticalAlign(admin.label[19], "center")
        admin.label[20] = guiCreateLabel(388, 35, 378, 26, "Main Player Actions", false, admin.tab[1])
        guiSetFont(admin.label[20], "clear-normal")
        guiLabelSetColor(admin.label[20], 17, 209, 237)
        guiLabelSetHorizontalAlign(admin.label[20], "center", false)
        guiLabelSetVerticalAlign(admin.label[20], "center")
        admin.button[3] = guiCreateButton(388, 64, 119, 33, "Punish", false, admin.tab[1])
        guiSetFont(admin.button[3], "clear-normal")
        guiSetProperty(admin.button[3], "NormalTextColour", "FFAAAAAA")
        admin.button[4] = guiCreateButton(515, 64, 119, 33, "Default Mute", false, admin.tab[1])
        guiSetFont(admin.button[4], "clear-normal")
        guiSetProperty(admin.button[4], "NormalTextColour", "FFAAAAAA")
        admin.button[5] = guiCreateButton(644, 64, 119, 33, "Default Ban", false, admin.tab[1])
        guiSetFont(admin.button[5], "clear-normal")
        guiSetProperty(admin.button[5], "NormalTextColour", "FFAAAAAA")
        admin.button[6] = guiCreateButton(388, 103, 119, 33, "Freeze", false, admin.tab[1])
        guiSetFont(admin.button[6], "clear-normal")
        guiSetProperty(admin.button[6], "NormalTextColour", "FFAAAAAA")
        admin.button[7] = guiCreateButton(515, 103, 119, 33, "Unfreeze", false, admin.tab[1])
        guiSetFont(admin.button[7], "clear-normal")
        guiSetProperty(admin.button[7], "NormalTextColour", "FFAAAAAA")
        admin.button[8] = guiCreateButton(644, 103, 119, 33, "Slap", false, admin.tab[1])
        guiSetFont(admin.button[8], "clear-normal")
        guiSetProperty(admin.button[8], "NormalTextColour", "FFAAAAAA")
        admin.button[9] = guiCreateButton(388, 142, 119, 33, "Kick", false, admin.tab[1])
        guiSetFont(admin.button[9], "clear-normal")
        guiSetProperty(admin.button[9], "NormalTextColour", "FFAAAAAA")
        admin.button[10] = guiCreateButton(515, 142, 119, 33, "Reconnect", false, admin.tab[1])
        guiSetFont(admin.button[10], "clear-normal")
        guiSetProperty(admin.button[10], "NormalTextColour", "FFAAAAAA")
        admin.button[11] = guiCreateButton(644, 142, 119, 33, "Force Rules", false, admin.tab[1])
        guiSetFont(admin.button[11], "clear-normal")
        guiSetProperty(admin.button[11], "NormalTextColour", "FFAAAAAA")
        admin.button[12] = guiCreateButton(388, 181, 119, 33, "Destroy Veh", false, admin.tab[1])
        guiSetFont(admin.button[12], "clear-normal")
        guiSetProperty(admin.button[12], "NormalTextColour", "FFAAAAAA")
        admin.button[13] = guiCreateButton(515, 181, 119, 33, "Fix Vehicle", false, admin.tab[1])
        guiSetFont(admin.button[13], "clear-normal")
        guiSetProperty(admin.button[13], "NormalTextColour", "FFAAAAAA")
        admin.button[14] = guiCreateButton(644, 181, 119, 33, "Blow Vehicle", false, admin.tab[1])
        guiSetFont(admin.button[14], "clear-normal")
        guiSetProperty(admin.button[14], "NormalTextColour", "FFAAAAAA")
        admin.label[21] = guiCreateLabel(388, 217, 378, 26, "______________________________________________", false, admin.tab[1])
        guiSetFont(admin.label[21], "clear-normal")
        guiLabelSetColor(admin.label[21], 241, 3, 250)
        guiLabelSetVerticalAlign(admin.label[21], "center")
        admin.label[22] = guiCreateLabel(388, 243, 378, 26, "Misc Player Actions", false, admin.tab[1])
        guiSetFont(admin.label[22], "clear-normal")
        guiLabelSetColor(admin.label[22], 17, 209, 237)
        guiLabelSetHorizontalAlign(admin.label[22], "center", false)
        guiLabelSetVerticalAlign(admin.label[22], "center")
        admin.button[15] = guiCreateButton(388, 272, 119, 33, "Set Interior", false, admin.tab[1])
        guiSetFont(admin.button[15], "clear-normal")
        guiSetProperty(admin.button[15], "NormalTextColour", "FFAAAAAA")
        admin.edit[1] = guiCreateEdit(644, 272, 119, 31, "", false, admin.tab[1])
        admin.button[16] = guiCreateButton(515, 272, 119, 33, "Set Dimension", false, admin.tab[1])
        guiSetFont(admin.button[16], "clear-normal")
        guiSetProperty(admin.button[16], "NormalTextColour", "FFAAAAAA")
        admin.edit[2] = guiCreateEdit(644, 309, 119, 31, "", false, admin.tab[1])
        admin.button[17] = guiCreateButton(515, 309, 119, 33, "Give Weapon", false, admin.tab[1])
        guiSetFont(admin.button[17], "clear-normal")
        guiSetProperty(admin.button[17], "NormalTextColour", "FFAAAAAA")
        admin.button[18] = guiCreateButton(388, 309, 119, 33, "Give Vehicle", false, admin.tab[1])
        guiSetFont(admin.button[18], "clear-normal")
        guiSetProperty(admin.button[18], "NormalTextColour", "FFAAAAAA")
        admin.button[19] = guiCreateButton(388, 347, 119, 33, "Warp To", false, admin.tab[1])
        guiSetFont(admin.button[19], "clear-normal")
        guiSetProperty(admin.button[19], "NormalTextColour", "FFAAAAAA")
        admin.button[20] = guiCreateButton(515, 347, 119, 33, "Warp Player To", false, admin.tab[1])
        guiSetFont(admin.button[20], "clear-normal")
        guiSetProperty(admin.button[20], "NormalTextColour", "FFAAAAAA")
        admin.button[21] = guiCreateButton(644, 347, 119, 33, "Rename", false, admin.tab[1])
        guiSetFont(admin.button[21], "clear-normal")
        guiSetProperty(admin.button[21], "NormalTextColour", "FFAAAAAA")
        admin.button[22] = guiCreateButton(391, 383, 119, 33, "Give Health", false, admin.tab[1])
        guiSetFont(admin.button[22], "clear-normal")
        guiSetProperty(admin.button[22], "NormalTextColour", "FFAAAAAA")
        admin.button[23] = guiCreateButton(515, 383, 119, 33, "Give Armour", false, admin.tab[1])
        guiSetFont(admin.button[23], "clear-normal")
        guiSetProperty(admin.button[23], "NormalTextColour", "FFAAAAAA")
        admin.button[24] = guiCreateButton(644, 383, 119, 33, "Spectate", false, admin.tab[1])
        guiSetFont(admin.button[24], "clear-normal")
        guiSetProperty(admin.button[24], "NormalTextColour", "FFAAAAAA")
        admin.button[25] = guiCreateButton(391, 420, 119, 33, "Toggle Jetpack", false, admin.tab[1])
        guiSetFont(admin.button[25], "clear-normal")
        guiSetProperty(admin.button[25], "NormalTextColour", "FFAAAAAA")
        admin.button[26] = guiCreateButton(515, 420, 119, 33, "Set Skin", false, admin.tab[1])
        guiSetFont(admin.button[26], "clear-normal")
        guiSetProperty(admin.button[26], "NormalTextColour", "FFAAAAAA")
        admin.edit[3] = guiCreateEdit(644, 422, 119, 31, "", false, admin.tab[1])

        admin.tab[2] = guiCreateTab("Reports", admin.tabpanel[1])
        admin.tab[3] = guiCreateTab("Server Management", admin.tabpanel[1])

        admin.label[23] = guiCreateLabel(10, 5, 206, 25, "Aurora Admins", false, admin.tab[3])
        guiSetFont(admin.label[23], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[23], "center")
        admin.gridlist[2] = guiCreateGridList(6, 32, 457, 206, false, admin.tab[3])
        guiGridListAddColumn(admin.gridlist[2], "Nick", 0.2)
        guiGridListAddColumn(admin.gridlist[2], "Level", 0.2)
        guiGridListAddColumn(admin.gridlist[2], "Dev", 0.2)
        guiGridListAddColumn(admin.gridlist[2], "EM", 0.2)
        guiGridListAddColumn(admin.gridlist[2], "ACL", 0.2)
        admin.button[27] = guiCreateButton(467, 31, 143, 38, "Kick Admin", false, admin.tab[3])
        guiSetFont(admin.button[27], "clear-normal")
        guiSetProperty(admin.button[27], "NormalTextColour", "FFAAAAAA")
        admin.button[28] = guiCreateButton(613, 31, 143, 38, "De(Activate) Admin", false, admin.tab[3])
        guiSetProperty(admin.button[28], "NormalTextColour", "FFAAAAAA")
        admin.button[29] = guiCreateButton(467, 73, 143, 38, "Promote Admin", false, admin.tab[3])
        guiSetProperty(admin.button[29], "NormalTextColour", "FFAAAAAA")
        admin.button[30] = guiCreateButton(613, 73, 143, 38, "Demote Admin", false, admin.tab[3])
        guiSetProperty(admin.button[30], "NormalTextColour", "FFAAAAAA")
        admin.button[31] = guiCreateButton(467, 115, 143, 38, "Toggle Event Manager", false, admin.tab[3])
        guiSetProperty(admin.button[31], "NormalTextColour", "FFAAAAAA")
        admin.button[32] = guiCreateButton(613, 115, 143, 38, "Toggle Developer", false, admin.tab[3])
        guiSetProperty(admin.button[32], "NormalTextColour", "FFAAAAAA")
        admin.button[33] = guiCreateButton(467, 157, 143, 38, "Add to ACL", false, admin.tab[3])
        guiSetProperty(admin.button[33], "NormalTextColour", "FFAAAAAA")
        admin.button[34] = guiCreateButton(613, 157, 143, 38, "Remove from ACL", false, admin.tab[3])
        guiSetProperty(admin.button[34], "NormalTextColour", "FFAAAAAA")
        admin.button[35] = guiCreateButton(467, 200, 143, 38, "Add Assignment", false, admin.tab[3])
        guiSetProperty(admin.button[35], "NormalTextColour", "FFAAAAAA")
        admin.button[36] = guiCreateButton(613, 200, 143, 38, "Remove Assignment", false, admin.tab[3])
        guiSetProperty(admin.button[36], "NormalTextColour", "FFAAAAAA")
        admin.label[24] = guiCreateLabel(6, 244, 750, 22, "___________________________________________________________________________________________________________", false, admin.tab[3])
        admin.label[25] = guiCreateLabel(467, 6, 206, 25, "Admin Actions", false, admin.tab[3])
        guiSetFont(admin.label[25], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[25], "center")
        admin.label[26] = guiCreateLabel(6, 262, 206, 25, "Administration", false, admin.tab[3])
        guiSetFont(admin.label[26], "clear-normal")
        guiLabelSetVerticalAlign(admin.label[26], "center")
        admin.edit[4] = guiCreateEdit(6, 292, 133, 29, "Username", false, admin.tab[3])
        admin.edit[5] = guiCreateEdit(143, 292, 133, 29, "Nick", false, admin.tab[3])
        admin.radiobutton[4] = guiCreateRadioButton(6, 325, 133, 20, "Male", false, admin.tab[3])
        guiSetFont(admin.radiobutton[4], "clear-normal")
        admin.radiobutton[5] = guiCreateRadioButton(143, 325, 133, 20, "Female", false, admin.tab[3])
        guiSetFont(admin.radiobutton[5], "clear-normal")
        guiRadioButtonSetSelected(admin.radiobutton[5], true)
        admin.button[37] = guiCreateButton(281, 293, 132, 28, "Add Staff", false, admin.tab[3])
        guiSetFont(admin.button[37], "clear-normal")
        guiSetProperty(admin.button[37], "NormalTextColour", "FFAAAAAA")
        admin.edit[6] = guiCreateEdit(6, 351, 133, 27, "Password", false, admin.tab[3])
        admin.button[38] = guiCreateButton(144, 351, 132, 28, "Set Server Pass", false, admin.tab[3])
        guiSetFont(admin.button[38], "clear-normal")
        guiSetProperty(admin.button[38], "NormalTextColour", "FFAAAAAA")
        admin.button[39] = guiCreateButton(281, 351, 132, 28, "Toggle Password", false, admin.tab[3])
        guiSetFont(admin.button[39], "clear-normal")
        guiSetProperty(admin.button[39], "NormalTextColour", "FFAAAAAA")
        admin.checkbox[1] = guiCreateCheckBox(7, 396, 132, 18, "Disable Mainchat", false, false, admin.tab[3])
        guiSetFont(admin.checkbox[1], "clear-normal")
        admin.checkbox[2] = guiCreateCheckBox(144, 396, 132, 18, "Disable Advert", false, false, admin.tab[3])
        guiSetFont(admin.checkbox[2], "clear-normal")
        admin.checkbox[3] = guiCreateCheckBox(6, 424, 132, 18, "Disable Joining", false, false, admin.tab[3])
        guiSetFont(admin.checkbox[3], "clear-normal")
        admin.checkbox[4] = guiCreateCheckBox(144, 424, 132, 18, "Freeze All", false, false, admin.tab[3])
        guiSetFont(admin.checkbox[4], "clear-normal")
        admin.button[40] = guiCreateButton(467, 273, 143, 38, "Shutdown Server", false, admin.tab[3])
        guiSetProperty(admin.button[40], "NormalTextColour", "FFAAAAAA")
        admin.button[41] = guiCreateButton(613, 273, 143, 38, "Slap All", false, admin.tab[3])
        guiSetProperty(admin.button[41], "NormalTextColour", "FFAAAAAA")
        admin.button[42] = guiCreateButton(467, 317, 143, 38, "Rewards", false, admin.tab[3])
        guiSetProperty(admin.button[42], "NormalTextColour", "FFAAAAAA")
        admin.button[43] = guiCreateButton(613, 317, 143, 38, "Manage Groups", false, admin.tab[3])
        guiSetProperty(admin.button[43], "NormalTextColour", "FFAAAAAA")
        admin.button[44] = guiCreateButton(467, 361, 143, 38, "Development Mode", false, admin.tab[3])
        guiSetProperty(admin.button[44], "NormalTextColour", "FFAAAAAA")
        admin.button[45] = guiCreateButton(613, 361, 143, 38, "Maintenence Mode", false, admin.tab[3])
        guiSetProperty(admin.button[45], "NormalTextColour", "FFAAAAAA")
        admin.button[46] = guiCreateButton(467, 405, 143, 38, "Kick All", false, admin.tab[3])
        guiSetProperty(admin.button[46], "NormalTextColour", "FFAAAAAA")
        admin.button[47] = guiCreateButton(613, 405, 143, 38, "Reconnect All", false, admin.tab[3])
        guiSetProperty(admin.button[47], "NormalTextColour", "FFAAAAAA")

        admin.tab[4] = guiCreateTab("Accounts", admin.tabpanel[1])
        admin.tab[5] = guiCreateTab("Bans", admin.tabpanel[1])
        admin.tab[6] = guiCreateTab("Resources", admin.tabpanel[1])
        admin.tab[7] = guiCreateTab("Rooms", admin.tabpanel[1])
        admin.tab[8] = guiCreateTab("Logs", admin.tabpanel[1])

        admin.label[27] = guiCreateLabel(181, 26, 334, 26, "Your name (account): N/A (N/A)", false, admin.window[1])
        guiSetFont(admin.label[27], "clear-normal")
        guiLabelSetColor(admin.label[27], 16, 249, 4)
        guiLabelSetVerticalAlign(admin.label[27], "center")
        admin.label[28] = guiCreateLabel(181, 52, 334, 29, "Your Rank (privillages): L0 (ACL: Admin)", false, admin.window[1])
        guiSetFont(admin.label[28], "clear-normal")
        guiLabelSetColor(admin.label[28], 16, 249, 4)
        guiLabelSetVerticalAlign(admin.label[28], "center")
        admin.label[29] = guiCreateLabel(181, 81, 334, 29, "Your Duties: General Staff", false, admin.window[1])
        guiSetFont(admin.label[29], "clear-normal")
        guiLabelSetColor(admin.label[29], 16, 249, 4)
        guiLabelSetVerticalAlign(admin.label[29], "center")
        admin.label[30] = guiCreateLabel(515, 26, 438, 26, "Staff Pin: No current pins at this time.", false, admin.window[1])
        guiSetFont(admin.label[30], "clear-normal")
        guiLabelSetColor(admin.label[30], 245, 242, 7)
        guiLabelSetVerticalAlign(admin.label[30], "center")
        admin.label[31] = guiCreateLabel(515, 81, 334, 29, "Number of punishments: 0", false, admin.window[1])
        guiSetFont(admin.label[31], "clear-normal")
        guiLabelSetColor(admin.label[31], 17, 209, 237)
        guiLabelSetVerticalAlign(admin.label[31], "center")
        admin.label[32] = guiCreateLabel(515, 52, 334, 29, "Assignment: No current assignments.", false, admin.window[1])
        guiSetFont(admin.label[32], "clear-normal")
        guiLabelSetColor(admin.label[32], 245, 242, 7)
        guiLabelSetVerticalAlign(admin.label[32], "center")
        admin.button[48] = guiCreateButton(909, 26, 39, 25, "X", false, admin.window[1])
        guiSetFont(admin.button[48], "default-bold-small")
        guiSetProperty(admin.button[48], "NormalTextColour", "FFAAAAAA")    
    end
)

function panel_open()
	if (not guiGetVisible(admin.window[1])) then
		guiSetVisible(admin.window[1], true)
		showCursor(true, not isCursorShowing())
		guiSetInputMode("no_binds_when_editing")
	else
		guiSetVisible(admin.window[1], false)
		showCursor(false, not isCursorShowing())
		guiSetInputMode("allow_binds")
	end
end
addCommandHandler("admin", panel_open)