xtrashipweapon1 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon2 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon3 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon4 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon5 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon6 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon7 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon8 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon9 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon10 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon11 = createWeapon ("minigun", 0,0,0 )
xtrashipweapon12 = createWeapon ("minigun", 0,0,0 )
addEvent("shootxtrashipweapon1",true)
function shootxtrashipweapon1(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon1,9999)
setWeaponTarget ( xtrashipweapon1, p )
setWeaponState ( xtrashipweapon1, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon1, "ready" )
end
addEventHandler("shootxtrashipweapon1",getRootElement(),shootxtrashipweapon1)
addEvent("sshootxtrashipweapon1",true)
function sshootxtrashipweapon1(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon1, nil )
setWeaponState ( xtrashipweapon1, "ready" )
end
addEventHandler("sshootxtrashipweapon1",getRootElement(),sshootxtrashipweapon1)
addEvent("shootxtrashipweapon2",true)
function shootxtrashipweapon2(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon2,9999)
setWeaponTarget ( xtrashipweapon2, p )
setWeaponState ( xtrashipweapon2, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon2, "ready" )
end
addEventHandler("shootxtrashipweapon2",getRootElement(),shootxtrashipweapon2)
addEvent("sshootxtrashipweapon2",true)
function sshootxtrashipweapon2(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon2, nil )
setWeaponState ( xtrashipweapon2, "ready" )
end
addEventHandler("sshootxtrashipweapon2",getRootElement(),sshootxtrashipweapon2)
addEvent("shootxtrashipweapon3",true)
function shootxtrashipweapon3(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon3,9999)
setWeaponTarget ( xtrashipweapon3, p )
setWeaponState ( xtrashipweapon3, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon3, "ready" )
end
addEventHandler("shootxtrashipweapon3",getRootElement(),shootxtrashipweapon3)
addEvent("sshootxtrashipweapon3",true)
function sshootxtrashipweapon3(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon3, nil )
setWeaponState ( xtrashipweapon3, "ready" )
end
addEventHandler("sshootxtrashipweapon3",getRootElement(),sshootxtrashipweapon3)
addEvent("shootxtrashipweapon4",true)
function shootxtrashipweapon4(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon4,9999)
setWeaponTarget ( xtrashipweapon4, p )
setWeaponState ( xtrashipweapon4, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon4, "ready" )
end
addEventHandler("shootxtrashipweapon4",getRootElement(),shootxtrashipweapon4)
addEvent("sshootxtrashipweapon4",true)
function sshootxtrashipweapon4(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon4, nil )
setWeaponState ( xtrashipweapon4, "ready" )
end
addEventHandler("sshootxtrashipweapon4",getRootElement(),sshootxtrashipweapon4)
addEvent("shootxtrashipweapon5",true)
function shootxtrashipweapon5(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon5,9999)
setWeaponTarget ( xtrashipweapon5, p )
setWeaponState ( xtrashipweapon5, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon5, "ready" )
end
addEventHandler("shootxtrashipweapon5",getRootElement(),shootxtrashipweapon5)
addEvent("sshootxtrashipweapon5",true)
function sshootxtrashipweapon5(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon5, nil )
setWeaponState ( xtrashipweapon5, "ready" )
end
addEventHandler("sshootxtrashipweapon5",getRootElement(),sshootxtrashipweapon5)
addEvent("shootxtrashipweapon6",true)
function shootxtrashipweapon6(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon6,9999)
setWeaponTarget ( xtrashipweapon6, p )
setWeaponState ( xtrashipweapon6, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon6, "ready" )
end
addEventHandler("shootxtrashipweapon6",getRootElement(),shootxtrashipweapon6)
addEvent("sshootxtrashipweapon6",true)
function sshootxtrashipweapon6(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon6, nil )
setWeaponState ( xtrashipweapon6, "ready" )
end
addEventHandler("sshootxtrashipweapon6",getRootElement(),sshootxtrashipweapon6)
addEvent("shootxtrashipweapon7",true)
function shootxtrashipweapon7(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon7,9999)
setWeaponTarget ( xtrashipweapon7, p )
setWeaponState ( xtrashipweapon7, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon7, "ready" )
end
addEventHandler("shootxtrashipweapon7",getRootElement(),shootxtrashipweapon7)
addEvent("sshootxtrashipweapon7",true)
function sshootxtrashipweapon7(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon7, nil )
setWeaponState ( xtrashipweapon7, "ready" )
end
addEventHandler("sshootxtrashipweapon7",getRootElement(),sshootxtrashipweapon7)
addEvent("shootxtrashipweapon8",true)
function shootxtrashipweapon8(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon8,9999)
setWeaponTarget ( xtrashipweapon8, p )
setWeaponState ( xtrashipweapon8, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon8, "ready" )
end
addEventHandler("shootxtrashipweapon8",getRootElement(),shootxtrashipweapon8)
addEvent("sshootxtrashipweapon8",true)
function sshootxtrashipweapon8(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon8, nil )
setWeaponState ( xtrashipweapon8, "ready" )
end
addEventHandler("sshootxtrashipweapon8",getRootElement(),sshootxtrashipweapon8)
addEvent("shootxtrashipweapon9",true)
function shootxtrashipweapon9(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon9,9999)
setWeaponTarget ( xtrashipweapon9, p )
setWeaponState ( xtrashipweapon9, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon9, "ready" )
end
addEventHandler("shootxtrashipweapon9",getRootElement(),shootxtrashipweapon9)
addEvent("sshootxtrashipweapon9",true)
function sshootxtrashipweapon9(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon9, nil )
setWeaponState ( xtrashipweapon9, "ready" )
end
addEventHandler("sshootxtrashipweapon9",getRootElement(),sshootxtrashipweapon9)

addEvent("shootxtrashipweapon10",true)
function shootxtrashipweapon10(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon10,9999)
setWeaponTarget ( xtrashipweapon10, p )
setWeaponState ( xtrashipweapon10, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon10, "ready" )
end
addEventHandler("shootxtrashipweapon10",getRootElement(),shootxtrashipweapon10)
addEvent("sshootxtrashipweapon10",true)
function sshootxtrashipweapon10(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon10, nil )
setWeaponState ( xtrashipweapon10, "ready" )
end
addEventHandler("sshootxtrashipweapon10",getRootElement(),sshootxtrashipweapon10)
addEvent("shootxtrashipweapon11",true)
function shootxtrashipweapon11(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon11,9999)
setWeaponTarget ( xtrashipweapon11, p )
setWeaponState ( xtrashipweapon11, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon11, "ready" )
end
addEventHandler("shootxtrashipweapon11",getRootElement(),shootxtrashipweapon11)
addEvent("sshootxtrashipweapon11",true)
function sshootxtrashipweapon11(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon11, nil )
setWeaponState ( xtrashipweapon11, "ready" )
end
addEventHandler("sshootxtrashipweapon11",getRootElement(),sshootxtrashipweapon11)
addEvent("shootxtrashipweapon12",true)
function shootxtrashipweapon12(p,x,y,z,r)
setWeaponAmmo(xtrashipweapon12,9999)
setWeaponTarget ( xtrashipweapon12, p )
setWeaponState ( xtrashipweapon12, "firing" )
setTimer(setWeaponState,10000,1,xtrashipweapon12, "ready" )
end
addEventHandler("shootxtrashipweapon12",getRootElement(),shootxtrashipweapon12)
addEvent("sshootxtrashipweapon12",true)
function sshootxtrashipweapon12(p,x,y,z,r)
setWeaponTarget ( xtrashipweapon12, nil )
setWeaponState ( xtrashipweapon12, "ready" )
end
addEventHandler("sshootxtrashipweapon12",getRootElement(),sshootxtrashipweapon12)
addEvent("addxtrashipweapons",true)
function addxtrashipweapons(p,x,y,z,r)
attachElements( xtrashipweapon1, p, -6, 12, 1.5, 0, 0, 0 )
attachElements( xtrashipweapon2, p, 6, 12, 1.5, 0, 0, 0 )
attachElements( xtrashipweapon3, p, -9.1, 8, 7.3, 0, 0, 0 )
attachElements( xtrashipweapon4, p, 8.9, 8, 7.3, 0, 0, 0 )
attachElements( xtrashipweapon5, p, -12.3, -1, 5.5, 0, 0, 0 )
attachElements( xtrashipweapon6, p, 12.3, -1, 5.5, 0, 0, 0 )
attachElements( xtrashipweapon7, p, -12.3, -2.5, 5.5, 0, 0, 0 )
attachElements( xtrashipweapon8, p, 12.3, -2.5, 5.5, 0, 0, 0 )
attachElements( xtrashipweapon9, p, -7, -3.5, 5.5, 0, 0, 0 )
attachElements( xtrashipweapon10, p, 7, -3.5, 5.5, 0, 0, 0 )
attachElements( xtrashipweapon11, p, -2, -75, 3, 0, 0, 0 )
attachElements( xtrashipweapon12, p, 2, -75, 3, 0, 0, 0 )
end
addEventHandler("addxtrashipweapons",getRootElement(),addxtrashipweapons)
