local GUIEditor = {}
local clist = {}		
local screenW, screenH = guiGetScreenSize()

		staffmiscpanel = guiCreateWindow((screenW - 670) / 2, (screenH - 609) / 2, 670, 609, "AuroraRPG ~ Staff Knowledge", false)
        guiWindowSetSizable(staffmiscpanel, false)

        guiCreateLabel(83, 54, 563, 20, "Welcome to staff team knowledge panel, If you are a new staff in staff team then welcome.", false, staffmiscpanel)
        guiCreateLabel(47, 83, 580, 15, "In this panel, You will see the most useful commands you can use while managing your duty. Good Luck!", false, staffmiscpanel)
        clist =  guiCreateGridList(43, 158, 576, 407, false, staffmiscpanel)
        guiGridListAddColumn(clist, "Command", 0.5)
        guiGridListAddColumn(clist, "Function", 0.5)
        for i = 1, 29 do
            guiGridListAddRow(clist)
        end
        guiGridListSetItemText(clist, 0, 1, "/staff", false, false)
        guiGridListSetItemText(clist, 0, 2, "Moves you to staff duty", false, false)
        guiGridListSetItemText(clist, 1, 1, "/invis", false, false)
        guiGridListSetItemText(clist, 1, 2, "Makes/Removes you from invisible mode", false, false)
        guiGridListSetItemText(clist, 2, 1, "/vehinvis", false, false)
        guiGridListSetItemText(clist, 2, 2, "Makes/Removes your vehicle from invisible mode", false, false)
        guiGridListSetItemText(clist, 3, 1, "/glue", false, false)
        guiGridListSetItemText(clist, 3, 2, "Makes you glue at vehicle", false, false)
        guiGridListSetItemText(clist, 4, 1, "/unglue", false, false)
        guiGridListSetItemText(clist, 4, 2, "Makes you free from vehicle", false, false)
        guiGridListSetItemText(clist, 5, 1, "/dmgproof", false, false)
        guiGridListSetItemText(clist, 5, 2, "Makes your vehicle unable to get damaged", false, false)
        guiGridListSetItemText(clist, 6, 1, "/stream", false, false)
        guiGridListSetItemText(clist, 6, 2, "To stream music in your area", false, false)
        guiGridListSetItemText(clist, 7, 1, "/aur", false, false)
        guiGridListSetItemText(clist, 7, 2, "To talk privately with staff team", false, false)
        guiGridListSetItemText(clist, 8, 1, "/sup", false, false)
        guiGridListSetItemText(clist, 8, 2, "To talk privately with supporters team", false, false)
        guiGridListSetItemText(clist, 9, 1, "/setjob", false, false)
        guiGridListSetItemText(clist, 9, 2, "To set any player job", false, false)
        guiGridListSetItemText(clist, 10, 1, "/note", false, false)
        guiGridListSetItemText(clist, 10, 2, "To write staff note", false, false)
        guiGridListSetItemText(clist, 11, 1, "/wp", false, false)
        guiGridListSetItemText(clist, 11, 2, "To transport easily to most popular places", false, false)
        guiGridListSetItemText(clist, 12, 1, "/viewwep", false, false)
        guiGridListSetItemText(clist, 12, 2, "To see all player weapons", false, false)
        guiGridListSetItemText(clist, 13, 1, "/viewhouseweps", false, false)
        guiGridListSetItemText(clist, 13, 2, "To check all player house's weapons", false, false)
        guiGridListSetItemText(clist, 14, 1, "/staffhelp", false, false)
        guiGridListSetItemText(clist, 14, 2, "Makes yourself available for help", false, false)
        guiGridListSetItemText(clist, 15, 1, "/sbs", false, false)
        guiGridListSetItemText(clist, 15, 2, "Super brakes for vehicles", false, false)
        guiGridListSetItemText(clist, 16, 1, "/opendoor34", false, false)
        guiGridListSetItemText(clist, 16, 2, "To open/close dice event gates", false, false)
        guiGridListSetItemText(clist, 18, 1, "/vehfly", false, false)
        guiGridListSetItemText(clist, 18, 2, "To fly using your vehicle", false, false)
        guiGridListSetItemText(clist, 19, 1, "/superman", false, false)
        guiGridListSetItemText(clist, 19, 2, "To use staff superman", false, false)
        guiGridListSetItemText(clist, 20, 1, "P", false, false)
        guiGridListSetItemText(clist, 20, 2, "To open staff panel", false, false)
        guiGridListSetItemText(clist, 21, 1, "L", false, false)
        guiGridListSetItemText(clist, 21, 2, "To speed up your vehicle", false, false)
        guiGridListSetItemText(clist, 22, 1, "SHIFT", false, false)
        guiGridListSetItemText(clist, 22, 2, "To jump using your vehicle", false, false) 
        guiGridListSetItemText(clist, 23, 1, "/flip", false, false) 
        guiGridListSetItemText(clist, 23, 2, "To flip your vehicle", false, false) 
        guiGridListSetItemText(clist, 24, 1, "/openmaze", false, false) 
        guiGridListSetItemText(clist, 24, 2, "To open the maze gate", false, false)
        guiGridListSetItemText(clist, 25, 1, "/dj", false, false) 
        guiGridListSetItemText(clist, 25, 2, "To use public streamer", false, false)
        guiGridListSetItemText(clist, 26, 1, "/cskin 1/2", false, false) 
        guiGridListSetItemText(clist, 26, 2, "To change your skin to Batman or superman, L2+", false, false)
        guiGridListSetItemText(clist, 27, 1, "/wandpower", false, false) 
        guiGridListSetItemText(clist, 27, 2, "To move players/vehicles", false, false)
        guiGridListSetItemText(clist, 28, 1, "/dmmsgs", false, false) 
        guiGridListSetItemText(clist, 28, 2, "To open Deathmatch messages panel", false, false) 		
		guiWindowSetSizable(staffmiscpanel, false)
		guiSetVisible( staffmiscpanel, false )
		
		
bindKey( "F5", "down",
	function ()
	if (getTeamName(getPlayerTeam(localPlayer)) == "Staff") then
		if ( guiGetVisible( staffmiscpanel ) ) then
			guiSetVisible( staffmiscpanel, false )
			showCursor( false )
		else
			guiSetVisible( staffmiscpanel, true )
			showCursor( true )
			end
		end
	end
)
