
roxTable = {
	['Body'] = {199.688, -130.495, 1004.452, 195.132, -33.874, 979.081, 0},--added
	['Shirts'] = {199.626, -128.879, 1004.126, 196.547, -30.899, 984.364, 0},--added
	['Hair'] = {199.568, -128.232, 1004.379, 202.529, -34.013, 971.005, 0},--added
	['Trousers'] = {198.948, -130.601, 1003.966, 213.898, -32.888, 988.842, 0},--added
	['Shoes'] = {199.298, -128.525, 1003.674, 216.737, -69.64, 924.754, 0},-- added
	['Necklaces'] = {199.676, -128.244, 1004.161, 189.802, -34.277, 971.41, 0},--added
	['Watches'] = {200.354, -128.643, 1004.083, 148.466, -53.128, 964.021, 0},--added
	['Glasses'] = {199.698, -128.288, 1004.154, 188.207, -28.957, 1005.338, 0},--added
	['Hats'] = {199.684, -128.302, 1004.444, 190.935, -30.248, 986.873, 0},--added
	['Special outfit'] = {199.688, -130.495, 1004.452, 195.132, -33.874, 979.081, 0},
	['Tattoos Left Upper Arm'] = {200.552, -127.852, 1004.541, 122.161, -109.11, 945.35, 0},
	['Tattoos Left Lower Arm'] = {200.504, -128.032, 1004.104, 131.139, -89.513, 943.237, 0},
	['Tattoos Right Upper Arm'] = {198.92, -127.61, 1004.337, 274.356, -117.968, 939.402, 0},
	['Tattoos Right Lower Arm'] = {198.772, -127.75, 1003.821, 288.918, -104.969, 967.015, 0},
	['Tattoos Back'] = {199.741, -126.372, 1004.589, 193.97, -213.307, 955.507, 0},
	['Tattoos Left Chest'] = {199.605, -128.779, 1004.149, 198.896, -35.61, 967.831, 0},
	['Tattoos Right Chest'] = {199.605, -128.779, 1004.149, 198.896, -35.61, 967.831, 0},
	['Tattoos Stomach'] = {199.605, -128.779, 1004.149, 198.896, -35.61, 967.831, 0},
	--[''] = {},
}

types = {
	{ name = "Shirts", id = 0},
	{ name = "Hair", id = 1},
	{ name = "Trousers", id = 2},
	{ name = "Shoes", id = 3},
	{ name = "Necklaces", id = 13},
	{ name = "Watches", id = 14},
	{ name = "Glasses", id = 15},
	{ name = "Hats", id = 16},
	{ name = "Special outfit", id = 17},
	{ name = "Tattoos Left Upper Arm", id = 4},
	{ name = "Tattoos Left Lower Arm", id = 5},
	{ name = "Tattoos Right Upper Arm", id = 6},
	{ name = "Tattoos Right Lower Arm", id = 7},
	{ name = "Tattoos Back", id = 8},
	{ name = "Tattoos Left Chest", id = 9},
	{ name = "Tattoos Right Chest", id = 10},
	{ name = "Tattoos Stomach", id = 11},
}

clothes = {
	--Hats
	{ name = "Red Bandana", texture = "bandred", model = "bandana", id = 16, price = 150,modded=false},
	{ name = "Blue Bandana",texture = "bandblue", model = "bandana", id = 16, price = 150,modded=false},
	{ name = "Green Bandana",texture = "bandgang", model = "bandana", id = 16, price = 150,modded=false},
	{ name = "Black Bandana",texture = "bandblack", model = "bandana",id =  16, price = 150,modded=false},
	{ name = "Red Bandana Front",texture = "bandred2", model = "bandknots", id = 16, price = 150,modded=false},
	{ name = "Blue Bandana Front",texture = "bandblue2", model = "bandknots", id = 16, price = 150,modded=false},
	{ name = "Green Bandana Front",texture = "bandgang2", model = "bandknots", id = 16, price = 150,modded=false},
	{ name = "Black Bandana Front",texture = "bandblack2", model = "bandknots", id = 16, price = 150,modded=false},
	{ name = "Green Knit Cap",texture = "capknitgrn", model = "capknit", id = 16, price = 150,modded=false},
	{ name = "Trucker Cap",texture = "captruck", model = "captruck", id = 16, price = 150,modded=false},
	{ name = "Cowboy Hat 1",texture = "cowboy", model = "cowboy", id = 16, price = 150,modded=false},
	{ name = "Cowboy Hat 2",texture = "hattiger", model = "cowboy", id = 16, price = 150,modded=false},
	{ name = "Red Motorbike Helmet",texture = "helmet", model = "helmet", id = 16, price = 150,modded=false},
	{ name = "Blue Motorbike Helmet",texture = "moto", model = "moto", id = 16, price = 150,modded=false},
	{ name = "Boxing Cap",texture = "boxingcap", model = "boxingcap", id = 16, price = 150,modded=false},
	{ name = "Hockey Mask",texture = "hockey", model = "hockeymask", id = 16, price = 150,modded=false},
	{ name = "Green Cap Front",texture = "capgang", model = "cap", id = 16, price = 150,modded=false},
	{ name = "Green Cap Back",texture = "capgangback", model = "capback", id = 16, price = 150,modded=false},
	{ name = "Green Cap Side",texture = "capgangside", model = "capside", id = 16, price = 150,modded=false},
	{ name = "Green Cap Back 2",texture = "capgangover", model = "capovereye", id = 16, price = 150,modded=false},
	{ name = "Green Cap Up",texture = "capgangup", model = "caprimup", id = 16, price = 150,modded=false},
	{ name = "Biker Helmet",texture = "bikerhelmet", model = "bikerhelmet", id = 16, price = 150,modded=false},
	{ name = "Red Cap Front",texture = "capred", model = "cap", id = 16, price = 150,modded=false},
	{ name = "Red Cap Back",texture = "capredback", model = "capback", id = 16, price = 150,modded=false},
	{ name = "Red Cap Side",texture = "capredside", model = "capside", id = 16, price = 150,modded=false},
	{ name = "Red Cap Back 2",texture = "capredover", model = "capovereye", id = 16, price = 150,modded=false},
	{ name = "Red Cap Up",texture = "capredup", model = "caprimup", id = 16, price = 150,modded=false},
	{ name = "Blue Cap Front",texture = "capblue", model = "cap", id = 16, price = 150,modded=false},
	{ name = "Blue Cap Back",texture = "capblueback", model = "capback", id = 16, price = 150,modded=false},
	{ name = "Blue Cap Side",texture = "capblueside", model = "capside", id = 16, price = 150,modded=false},
	{ name = "Blue Cap Back 2",texture = "capblueover", model = "capovereye", id = 16, price = 150,modded=false},
	{ name = "Blue Cap Up",texture = "capblueup", model = "caprimup", id = 16, price = 150,modded=false},
	{ name = "Black Beanie",texture = "skullyblk", model = "skullycap", id = 16, price = 150,modded=false},
	{ name = "White skull hat",texture = "skullygrn", model = "skullycap", id = 16, price = 150,modded=true},
	{ name = "Black Sunhat",texture = "hatmancblk", model = "hatmanc", id = 16, price = 150,modded=false},
	{ name = "Striped Sunhat",texture = "hatmancplaid", model = "hatmanc", id = 16, price = 150,modded=false},
	{ name = "Yellow Cap Front",texture = "capzip", model = "cap", id = 16, price = 150,modded=false},
	{ name = "Yellow Cap Back",texture = "capzipback", model = "capback", id = 16, price = 150,modded=false},
	{ name = "Yellow Cap Side",texture = "capzipside", model = "capside", id = 16, price = 150,modded=false},
	{ name = "Yellow Cap Back 2",texture = "capzipover", model = "capovereye", id = 16, price = 150,modded=false},
	{ name = "Red Cap Up",texture = "capzipup", model = "caprimup", id = 16, price = 150,modded=false},
	{ name = "Red Beret",texture = "beretred", model = "beret", id = 16, price = 150,modded=false},
	{ name = "Black Beret",texture = "beretblk", model = "beret", id = 16, price = 150,modded=false},
	{ name = "Black Beret",texture = "capblk", model = "cap", id = 16, price = 150,modded=false},
	{ name = "Black Cap Back",texture = "capblkback", model = "capback", id = 16, price = 150,modded=false},
	{ name = "Black Cap Side",texture = "capblkside", model = "capside", id = 16, price = 150,modded=false},
	{ name = "Black Cap Back 2",texture = "capblkover", model = "capovereye", id = 16, price = 150,modded=false},
	{ name = "Black Cap Up",texture = "capblkup", model = "caprimup", id = 16, price = 150,modded=false},
	{ name = "Dark Detective  Hat",texture = "trilbydrk", model = "trilby", id = 16, price = 150,modded=false},
	{ name = "Light Detective Hat",texture = "trilbylght", model = "trilby", id = 16, price = 150,modded=false},
	{ name = "Black Bowler",texture = "bowler", model = "bowler", id = 16, price = 150,modded=false},
	{ name = "Red Bowler",texture = "bowlerred", model = "bowler", id = 16, price = 150,modded=false},
	{ name = "Blue Bowler",texture = "bowlerblue", model = "bowler", id = 16, price = 150,modded=false},
	{ name = "Yellow Bowler",texture = "bowleryellow", model = "bowler", id = 16, price = 150,modded=false},
	{ name = "Boater Hat 1",texture = "boater", model = "boater", id = 16, price = 150,modded=false},
	{ name = "Green Bowler",texture = "bowlergang", model = "bowler", id = 16, price = 150,modded=false},
	{ name = "Boater Hat 2",texture = "boaterblk", model = "boater", id = 16, price = 150,modded=false},
	--Shirts
	{ name = "No Shirt",texture = "player_torso", model = "torso", id = 0, price = 50,modded=false},
	{ name = "G unit Tank Vest",texture = "vestblack", model = "vest", id = 0, price = 250,modded=true},
	{ name = "G Unit Tank Vest",texture = "vest", model = "vest", id = 0, price = 250,modded=true},
	{ name = "Striped T-Shirt",texture = "tshirt2horiz", model = "tshirt2", id = 0, price = 250,modded=false},
	{ name = "Barcalon Shirt",texture = "tshirtwhite", model = "tshirt", id = 0, price = 250,modded=true},
	{ name = "Weed T-Shirt",texture = "tshirtilovels", model = "tshirt",id = 0, price = 250,modded=true},
	{ name = "Hope T-Shirt",texture = "tshirtblunts", model = "tshirt", id = 0, price = 250,modded=true},
	{ name = "Red Checkered Shirt",texture = "shirtbplaid", model = "shirtb", id = 0, price = 250,modded=false},
	{ name = "Blue Checkered Shirt",texture = "shirtbcheck", model = "shirtb", id = 0, price = 250,modded=false},
	{ name = "Shirt & T-Shirt Combination",texture = "field", model = "field", id = 0, price = 250,modded=false},
	{ name = "Green T-Shirt",texture = "tshirterisyell", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "LOL Shirt",texture = "tshirterisorn", model = "tshirt", 0, price = 250,modded=true},
	{ name = "Black Training",texture = "trackytop2eris", model = "trackytop1", id = 0, price = 250,modded=true},
	{ name = "Red/White Jacket",texture = "bbjackrim", model = "bbjack", id = 0, price = 250,modded=false},
	{ name = "Rockstar Jacket",texture = "bballjackrstar", model = "bbjack", id = 0, price = 250,modded=false},
	{ name = "Basketball Jersey 1",texture = "baskballdrib", model = "baskball", id = 0, price = 250,modded=false},
	{ name = "Basketball Jersey 2",texture = "baskballrim", model = "baskball", id = 0, price = 250,modded=false},
	{ name = "69er's Jersey",texture = "sixtyniners", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Bandits Baseball Jersey",texture = "bandits", model = "baseball", id = 0, price = 250,modded=false},
	{ name = "Red ProLaps T-Shirt",texture = "tshirtprored", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Black ProLaps T-Shirt",texture = "tshirtproblk", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Biker hoody",texture = "trackytop1pro", model = "trackytop1", id = 0, price = 250,modded=true},
	{ name = "Hockey Jersey",texture = "hockeytop", model = "sweat", id = 0, price = 250,modded=false},
	{ name = "ProLaps White Sleeve",texture = "bbjersey", model = "sleevt", id = 0, price = 250,modded=false},
	{ name = "Shellsuit Tracktop",texture = "shellsuit", model = "trackytop1", id = 0, price = 250,modded=false},
	{ name = "White TruReligion Shirt",texture = "tshirtheatwht", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Bobo Monkey T-Shirt", texture = "tshirtbobomonk", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Gangnam style shirt", texture = "tshirtbobored", model = "tshirt", id = 0, price = 250,modded=true},
	{ name = "Base-5 T-Shirt", texture = "tshirtbase5", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "SubUrban T-Shirt", texture = "tshirtsuburb", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "QuickSilver Hoodie", texture = "hoodyamerc", model = "hoodya", id = 0, price = 250,modded=false},
	{ name = "Base-5 Hoody", texture = "hoodyabase5", model = "hoodya", id = 0, price = 250,modded=false},
	{ name = "Rockstar Hoody", texture = "hoodyarockstar", model = "hoodya", id = 0, price = 250,modded=false},
	{ name = "White/Blue T-Shirt Coat", texture = "wcoatblue", model = "wcoat", id = 0, price = 250,modded=false},
	{ name = "Military Green Shirt", texture = "coach", model = "coach", id = 0, price = 250,modded=false},
	{ name = "Semi Military Green Shirt", texture = "coachsemi", model = "coach", id = 0, price = 250,modded=false},
	{ name = "Rockstar Sweater", texture = "sweatrstar", model = "sweat", id = 0, price = 250,modded=false},
	{ name = "Street fighter Hoody", texture = "hoodyAblue", model = "hoodyA", id = 0, price = 250,modded=true},
	{ name = "Prtotype Hoody", texture = "hoodyAblack", model = "hoodyA", id = 0, price = 250,modded=true},
	{ name = "Vans Hoody", texture = "hoodyAgreen", model = "hoodyA", id = 0, price = 250,modded=true},
	{ name = "Brown Sleeve Shirt", texture = "sleevtbrown", model = "sleevt", id = 0, price = 250,modded=false},
	{ name = "Light Blue Shirt", texture = "shirtablue", model = "shirta", id = 0, price = 250,modded=false},
	{ name = "Light Yellow Shirt", texture = "shirtayellow", model = "shirta", id = 0, price = 250,modded=false},
	{ name = "Grey Shirt", texture = "shirtagrey", model = "shirta", id = 0, price = 250,modded=false},
	{ name = "Green Shirt", texture = "shirtbgang", model = "shirtb", id = 0, price = 250,modded=false},
	{ name = "GO Swagg", texture = "tshirtzipcrm", model = "tshirt", id = 0, price = 250,modded=true},
	{ name = "Grey ZIP T-Shirt", texture = "tshirtzipgry", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Faded Demin Jacket", texture = "denimfade", model = "denim", id = 0, price = 250,modded=false},
	{ name = "Bowling T-Shirt", texture = "bowling", model = "hawaii", id = 0, price = 250,modded=false},
	{ name = "Beige Hoody Jacket", texture = "hoodjackbeige", model = "hoodjack", id = 0, price = 250,modded=false},
	{ name = "Gold Basketball Jersey", texture = "baskballloc", model = "baskball", id = 0, price = 250,modded=false},
	{ name = "Handcuff's T-Shirt", texture = "tshirtlocgrey", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Grey Uzi T-Shirt", texture = "tshirtmaddgrey", model = "tshirt", id = 0, price = 250,modded=false},
	{ name = "Ninja T-Shirt", texture = "tshirtmaddgrn", model = "tshirt", id = 0, price = 250,modded=true},
	{ name = "Grey Suit Jacket", texture = "suit1grey", model = "suit1", id = 0, price = 250,modded=false},
	{ name = "Black Mafia Jacket", texture = "suit1blk", model = "suit1", id = 0, price = 250,modded=true},
	{ name = "Leather Jacket", texture = "leather", model = "leather", id = 0, price = 250,modded=false},
	{ name = "Painter Jacket", texture = "painter", model = "painter", id = 0, price = 250,modded=false},
	{ name = "White Hawaii Shirt", texture = "hawaiiwht", model = "hawaii", id = 0, price = 250,modded=false},
	{ name = "Tommy Shirt", texture = "hawaiired", model = "hawaii", id = 0, price = 250,modded=true},
	{ name = "Sport's Tracktop", texture = "sportjack", model = "trackytop1", id = 0, price = 250,modded=false},
	{ name = "Red Suit Jacket", texture = "suit1red", model = "suit1", id = 0, price = 250,modded=false},
	{ name = "Blue Suit Jacket", texture = "suit1blue", model = "suit1", id = 0, price = 250,modded=false},
	{ name = "Yellow Suit Jacket", texture = "suit1yellow", model = "suit1", id = 0, price = 250,modded=false},
	{ name = "Green Tuxedo Jacket", texture = "suit2grn", model = "suit2", id = 0, price = 250,modded=false},
	{ name = "Black Tuxedo Jacket", texture = "tuxedo", model = "suit2", id = 0, price = 250,modded=false},
	{ name = "Green Suit Jacket", texture = "suit1gang", model = "suit1", id = 0, price = 250,modded=false},
	{ name = "Blue R Sleeve", texture = "letter", model = "sleevt", id = 0, price = 250,modded=false},
	--Trousers
	{ name = "No Trousers",texture = "player_legs", model = "legs", id = 2, price = 50,modded=false},
	{ name = "Black Boxer Briefs",texture = "legsblack", model = "legs", id = 2, price = 750,modded=false},
	{ name = "Hearted Boxer Briefs",texture = "legsheart", model = "legs", id = 2, price = 750,modded=false},
	{ name = "Camo Green Trousers",texture = "worktrcamogrn", model = "worktr", id = 2, price = 750,modded=false},
	{ name = "Camo Grey Trousers",texture = "worktrcamogry", model = "worktr", id = 2, price = 750,modded=false},
	{ name = "Grey Cargopants",texture = "worktrgrey", model = "worktr", id = 2, price = 750,modded=false},
	{ name = "Khaki Cargopants",texture = "worktrkhaki", model = "worktr", id = 2, price = 750,modded=false},
	{ name = "Black traning pants",texture = "tracktr", model = "tracktr", id = 2, price = 750,modded=true},
	{ name = "Navy Blue Trackpants",texture = "tracktreris", model = "tracktr", id = 2, price = 750,modded=false},
	{ name = "Tommy Jeans",texture = "jeansdenim", model = "jeans", id = 2, price = 750,modded=true},
	{ name = "Biege Khakis",texture = "biegetr", model = "chinosb", id = 2, price = 750,modded=false},
	{ name = "Biker pants",texture = "tracktrpro", model = "tracktr", id = 2, price = 750,modded=true},
	{ name = "GO Swagg",texture = "tracktrwhstr", model = "tracktr", id = 2, price = 750,modded=true},
	{ name = "Blue Trackpants",texture = "tracktrblue", model = "tracktr", id = 2, price = 750,modded=false},
	{ name = "Green Trackpants",texture = "tracktrgang", model = "tracktr", id = 2, price = 750,modded=false},
	{ name = "Barcalon Shorts",texture = "bbshortwht", model = "boxingshort",id =  2, price = 750,modded=true},
	{ name = "Blood Red Boxing Shorts",texture = "boxshort", model = "boxingshort", id = 2, price = 750,modded=false},
	{ name = "Regular Red Boxing Shorts",texture = "bbshortred", model = "boxingshort", id = 2, price = 750,modded=false},
	{ name = "Muli-Color Trackpants",texture = "shellsuittr", model = "tracktr", id = 2, price = 750,modded=false},
	{ name = "Grey Cargoshorts",texture = "shortsgrey", model = "shorts", id = 2, price = 750,modded=false},
	{ name = "Khaki Cargoshorts",texture = "shortskhaki", model = "shorts", id = 2, price = 750,modded=false},
	{ name = "Green Shorts 1",texture = "chongergang", model = "chonger", id = 2, price = 750,modded=false},
	{ name = "Red Shorts",texture = "chongerred", model = "chonger", id = 2, price = 750,modded=false},
	{ name = "Blue Shorts",texture = "chongerblue", model = "chonger", id = 2, price = 750,modded=false},
	{ name = "Green Shorts 2",texture = "shortsgang", model = "shorts", id = 2, price = 750,modded=false},
	{ name = "Denim Green Jeans",texture = "denimsgang", model = "jeans", id = 2, price = 750,modded=false},
	{ name = "Denim Red Jeans",texture = "denimsred", model = "jeans", id = 2, price = 750,modded=false},
	{ name = "Biege Chinos",texture = "chinosbiege", model = "chinosb", id = 2, price = 750,modded=false},
	{ name = "Khaki Chinos",texture = "chinoskhaki", model = "chinosb", id = 2, price = 750,modded=false},
	{ name = "Chino Shorts",texture = "cutoffchinos", model = "shorts", id = 2, price = 750,modded=false},
	{ name = "Blue Chino Shorts",texture = "cutoffchinosblue", model = "shorts", id = 2, price = 750,modded=false},
	{ name = "Black Chinos",texture = "chinosblack", model = "chinosb", id = 2, price = 750,modded=false},
	{ name = "Blue Chinos",texture = "chinosblue", model = "chinosb", id = 2, price = 750,modded=false},
	{ name = "Leather Jeans 1",texture = "leathertr", model = "leathertr", id = 2, price = 750,modded=false},
	{ name = "Leather Jeans 2",texture = "leathertrchaps", model = "leathertr", id = 2, price = 750,modded=false},
	{ name = "Grey Suit Pants",texture = "suit1trgrey", model = "suit1tr", id = 2, price = 750,modded=false},
	{ name = "Black Suit Pants",texture = "suit1trblk", model = "suit1tr", id = 2, price = 750,modded=false},
	{ name = "Demin Cut-Off Shorts",texture = "cutoffdenims", model = "shorts", id = 2, price = 750,modded=false},
	{ name = "Red Suit Pants",texture = "suit1trred", model = "suit1tr", id = 2, price = 750,modded=false},
	{ name = "Blue Suit Pants",texture = "suit1trblue", model = "suit1tr", id = 2, price = 750,modded=false},
	{ name = "Gold Suit Pants",texture = "suit1tryellow", model = "suit1tr", id = 2, price = 750,modded=false},
	{ name = "Green Tuxedo Pants",texture = "suit1trgreen", model = "suit1tr", id = 2, price = 750,modded=false},
	{ name = "Black Tuxedo Pants",texture = "suit1trblk2", model = "suit1tr", id = 2, price = 750,modded=false},
	{ name = "Green Suit Pants",texture = "suit1trgang", model = "suit1tr", id = 2, price = 750,modded=false},
	--Shoes
	{ name = "No Shoes", texture = "foot", model = "feet", id = 3, price = 50,modded=false},
	{ name = "Cowboy Boots", texture = "cowboyboot2", model = "biker", id = 3, price = 150,modded=false},
	{ name = "White & Grey BasketBall Shoes", texture = "bask2semi", model = "bask1", id = 3, price = 275,modded=false},
	{ name = "White Basketball Shoes", texture = "bask1eris", model = "bask1", id = 3, price = 275,modded=false},
	{ name = "Green Sneakers", texture = "sneakerbincgang", model = "sneaker", id = 3, price = 150,modded=false},
	{ name = "Black Sneakers", texture = "sneakerbincblk", model = "sneaker", id = 3, price = 150,modded=false},
	{ name = "Black Sandals", texture = "sandal", model = "flipflop", id = 3, price = 50,modded=false},
	{ name = "Black Sandals w/th Socks", texture = "sandalsock", model = "flipflop", id = 3, price = 100,modded=false},
	{ name = "Black & Blue Flip-Flops", texture = "flipflop", model = "flipflop", id = 3, price = 100,modded=false},
	{ name = "White & Blue Hi-Tops", texture = "hitop", model = "bask1", id = 3, price = 500,modded=false},
	{ name = "Black Converse Shoes 1", texture = "convproblk", model = "conv", id = 3, price = 375,modded=false},
	{ name = "Blue Converse Shoes", texture = "convproblu", model = "conv", id = 3, price = 350,modded=false},
	{ name = "Green Converse Shoes", texture = "convprogrn", model = "conv", id = 3, price = 350,modded=false},
	{ name = "Red Sneakers", texture = "sneakerprored", model = "sneaker", id = 3, price = 350,modded=false},
	{ name = "Blue Sneakers", texture = "sneakerproblu", model = "sneaker", id = 3, price = 350,modded=false},
	{ name = "White Sneakers 1", texture = "sneakerprowht", model = "sneaker", id = 3, price = 350,modded=false},
	{ name = "White & Red Basketball Shoes", texture = "bask1prowht", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Black Basketball Shoes", texture = "bask1problk", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Boxing Shoes", texture = "boxingshoe", model = "biker", id = 3, price = 350,modded=false},
	{ name = "Black Converse Shoes 2", texture = "convheatblk", model = "conv", id = 3, price = 350,modded=false},
	{ name = "Red Converse Shoes", texture = "convheatred", model = "conv", id = 3, price = 350,modded=false},
	{ name = "Orange Converse Shoes", texture = "convheatorn", model = "conv", id = 3, price = 350,modded=false},
	{ name = "White Sneakers", texture = "sneakerheatwht", model = "sneaker", id = 3, price = 350,modded=false},
	{ name = "Grey Sneakers", texture = "sneakerheatgry", model = "sneaker", id = 3, price = 350,modded=false},
	{ name = "Black & Grey Sneakers", texture = "sneakerheatblk", model = "sneaker", id = 3, price = 350,modded=false},
	{ name = "White Sneakers 2", texture = "bask2heatwht", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Blue & White Basketball Shoes", texture = "bask2heatband", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Grey Basketball Shoes", texture = "timbergrey", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Red Basketball Shoes", texture = "timberred", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Brown Hiking Shoes", texture = "timberfawn", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Green Hiking Shoes", texture = "timberhike", model = "bask1", id = 3, price = 350,modded=false},
	{ name = "Black & White Cowboy Boots", texture = "cowboyboot", model = "biker", id = 3, price = 350,modded=false},
	{ name = "Biker Boots", texture = "biker", model = "biker", id = 3, price = 350,modded=true},
	{ name = "Snake Boots", texture = "snakeskin", model = "biker", id = 3, price = 350,modded=false},
	{ name = "Black Dress Shoes", texture = "shoedressblk", model = "shoe", id = 3, price = 350,modded=false},
	{ name = "Brown Dress Shoes", texture = "shoedressbrn", model = "shoe", id = 3, price = 350,modded=false},
	{ name = "Black & White Shoes", texture = "shoespatz", model = "shoe", id = 3, price = 350,modded=false},
	--Hair
	{ name = "Regular Hair", texture = "player_face", model = "head", id = 1, price = 150,modded=false},
	{ name = "Blond Hair", texture = "hairblond", model = "head", id = 1, price = 150,modded=false},
	{ name = "Red Hair", texture = "hairred", model = "head", id = 1, price = 150,modded=false},
	{ name = "Blue Hair", texture = "hairblue", model = "head", id = 1, price = 150,modded=false},
	{ name = "Green Hair", texture = "hairgreen", model = "head", id = 1, price = 150,modded=false},
	{ name = "Pink Hair", texture = "hairpink", model = "head", id = 1, price = 150,modded=false},
	{ name = "Bald", texture = "bald", model = "head", id = 1, price = 150,modded=false},
	{ name = "Bald w/th Beard", texture = "baldbeard", model = "head", id = 1, price = 150,modded=false},
	{ name = "Bald w/th Stash", texture = "baldtash", model = "head", id = 1, price = 150,modded=false},
	{ name = "Bald w/th Goatee", texture = "baldgoatee", model = "head", id = 1, price = 150,modded=false},
	{ name = "High Fade", texture = "highfade", model = "head", id = 1, price = 150,modded=false},
	{ name = "High Afro", texture = "highafro", model = "highafro", id = 1, price = 150,modded=false},
	{ name = "Wedge", texture = "wedge", model = "wedge", id = 1, price = 150,modded=false},
	{ name = "Slope", texture = "slope", model = "slope", id = 1, price = 150,modded=false},
	{ name = "Curls", texture = "jhericurl", model = "jheri", id = 1, price = 150,modded=false},
	{ name = "Cornrows", texture = "cornrows", model = "cornrows", id = 1, price = 150,modded=false},
	{ name = "Blondrows", texture = "cornrowsb", model = "cornrows", id = 1, price = 150,modded=false},
	{ name = "Tramline", texture = "tramline", model = "tramline", id = 1, price = 150,modded=false},
	{ name = "Groove Cut", texture = "groovecut", model = "groovecut", id = 1, price = 150,modded=true},
	{ name = "Mohawk", texture = "mohawk", model = "mohawk", id = 1, price = 150,modded=false},
	{ name = "Blond Mohawk", texture = "mohawkblond", model = "mohawk", id = 1, price = 150,modded=false},
	{ name = "Pink Mohawk", texture = "mohawkpink", model = "mohawk", id = 1, price = 150,modded=false},
	{ name = "Mohawk w/th Beard", texture = "mohawkbeard", model = "mohawk", id = 1, price = 150,modded=false},
	{ name = "Afro", texture = "afro", model = "afro", id = 1, price = 150,modded=false},
	{ name = "Afro w/th Stash", texture = "afrotash", model = "afro", id = 1, price = 150,modded=false},
	{ name = "Afro w/th Goatee", texture = "afrobeard", model = "afro", id = 1, price = 150,modded=false},
	{ name = "Blond Afro", texture = "afroblond", model = "afro", id = 1, price = 150,modded=false},
	{ name = "Flat Top", texture = "flattop", model = "flattop", id = 1, price = 150,modded=false},
	{ name = "Elvis Hair", texture = "elvishair", model = "elvishair", id = 1, price = 150,modded=false},
	{ name = "Regular w/th Beard", texture = "beard", model = "head", id = 1, price = 150,modded=false},
	{ name = "Regular w/th Stash", texture = "tash", model = "head", id = 1, price = 150,modded=false},
	{ name = "Regular w/th Goatee", texture = "goatee", model = "head", id = 1, price = 150,modded=false},
	{ name = "Afro w/th Goatee", texture = "afrogoatee", model = "afro", id = 1, price = 150,modded=false},
	--Extras
	{ name = "Spiderman", texture = "gimpleg", model = "gimpleg", id = 17, price = 1250,modded=true},
	{ name = "Valet", texture = "valet", model = "valet", id = 17, price = 1250,modded=false},
	{ name = "Croupier", texture = "croupier", model = "valet", id = 17, price = 1250,modded=false},
	{ name = "Country", texture = "countrytr", model = "countrytr", id = 17, price = 1250,modded=false},
	{ name = "Police", texture = "policetr", model = "policetr", id = 17, price = 1250,modded=false},
	{ name = "Balaclava", texture = "balaclava", model = "balaclava", id = 17, price = 1250,modded=false},
	{ name = "Pimpsuit", texture = "pimptr", model = "pimptr", id = 17, price = 1250,modded=false},
	{ name = "Mech/Racer", texture = "garageleg", model = "garagetr", id = 17, price = 1250,modded=false},
	{ name = "Medic", texture = "medictr", model = "medictr", id = 17, price = 1250,modded=false},
	--Glasses
	{ name = "Fake Nose", texture = "groucho", model = "grouchos", id = 15, price = 375,modded=false},
	{ name = "Zorro", texture = "zorro", model = "zorromask", id = 15, price = 375,modded=false},
	{ name = "Eyepatch", texture = "eyepatch", model = "eyepatch", id = 15, price = 375,modded=false},
	{ name = "Glasses 1", texture = "glasses01", model = "glasses01", id = 15, price = 375,modded=false},
	{ name = "Glasses 4", texture = "glasses04", model = "glasses04", id = 15, price = 375,modded=false},
	{ name = "Red Band Mask", texture = "bandred3", model = "bandmask", id = 15, price = 375,modded=false},
	{ name = "Blue Band Mask", texture = "bandblue3", model = "bandmask", id = 15, price = 375,modded=false},
	{ name = "Green Band Mask", texture = "bandgang3", model = "bandmask", id = 15, price = 375,modded=false},
	{ name = "Black Band Mask", texture = "bandblack3", model = "bandmask", id = 15, price = 375,modded=false},
	{ name = "Glasses 1 Dark", texture = "glasses01dark", model = "glasses01", id = 15, price = 375,modded=false},
	{ name = "Glasses 4 Dark", texture = "glasses04dark", model = "glasses04", id = 15, price = 375,modded=false},
	{ name = "Glasses 3", texture = "glasses03", model = "glasses03", id = 15, price = 375,modded=false},
	{ name = "Glasses 3 Red", texture = "glasses03red", model = "glasses03", id = 15, price = 375,modded=false},
	{ name = "Glasses 3 Blue", texture = "glasses03blue", model = "glasses03", id = 15, price = 375,modded=false},
	{ name = "Glasses 3 Dark", texture = "glasses03dark", model = "glasses03", id = 15, price = 375,modded=false},
	{ name = "Glasses 5 Dark", texture = "glasses05dark", model = "glasses03", id = 15, price = 375,modded=false},
	{ name = "Glasses 5", texture = "glasses05", model = "glasses03", id = 15, price = 375,modded=false},
	--Watches
	{ name = "Pink Watch", texture = "watchpink", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Gold Watch", texture = "watchyellow", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Blue Watch", texture = "watchpro", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Black Watch", texture = "watchpro2", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Round Watch", texture = "watchsub1", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Green Watch", texture = "watchsub2", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Silver Watch", texture = "watchzip1", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Bronze Watch", texture = "watchzip2", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Round Gold", texture = "watchgno", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Silver Watch", texture = "watchgno2", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Gold/Silver Watch", texture = "watchcro", model = "watch", id = 14, price = 375,modded=false},
	{ name = "Round Silver", texture = "watchcro2", model = "watch", id = 14, price = 375,modded=false},
	--Necklaces
	{ name = "Dogtags", texture = "dogtag", model = "neck", id = 13, price = 480,modded=false},
	{ name = "Africa", texture = "neckafrica", model = "neck", id = 13, price = 480,modded=false},
	{ name = "Stopwatch", texture = "stopwatch", model = "neck", id = 13, price = 480,modded=false},
	{ name = "Saints", texture = "necksaints", model = "neck", id = 13, price = 480,modded=false},
	{ name = "Weed", texture = "neckhash", model = "neck", id = 13, price = 480,modded=false},
	{ name = "Silver Chain 1", texture = "necksilver", model = "neck2", id = 13, price = 480,modded=false},
	{ name = "Gold Chain 1", texture = "neckgold", model = "neck2", id = 13, price = 480,modded=false},
	{ name = "Silver Chain 2", texture = "neckropes", model = "neck2", id = 13, price = 480,modded=false},
	{ name = "Gold Chain 2", texture = "neckropeg", model = "neck2", id = 13, price = 480,modded=false},
	{ name = "LS Necklace", texture = "neckls", model = "neck", id = 13, price = 480,modded=false},
	{ name = "Dollar", texture = "neckdollar", model = "neck", id = 13, price = 480,modded=false},
	{ name = "Cross", texture = "neckcross", model = "neck", id = 13, price = 480,modded=false},
	-- Tattos
	{ name = "Weed", texture = "4WEED", model = "4weed", id = 4, price = 880,modded=false},
	{ name = "RIP", texture = "4RIP", model = "4rip", id = 4, price = 580,modded=false},
	{ name = "Spider", texture = "4SPIDER", model = "4spider", id = 4, price = 1200,modded=false},
	{ name = "Gun", texture = "5GUN", model = "5gun", id = 5, price = 880 ,modded=false},
	{ name = "Cross", texture = "5CROSS", model = "5cross", id = 5, price = 3580 ,modded=false},
	{ name = "Cross2", texture = "5CROSS2", model = "5cross2", id = 5, price = 1100 ,modded=false},
	{ name = "Cross3", texture = "5CROSS3", model = "5cross3", id = 5, price = 500 ,modded=false},
	{ name = "Aztec", texture = "6AZTEC", model = "6aztec", id = 6 , price = 300 ,modded=false},
	{ name = "Crown", texture = "6CROWN", model = "6crown", id = 6 , price = 600 ,modded=false},
	{ name = "Clown", texture = "6CLOWN", model = "6clown", id = 6 , price = 780 ,modded=false},
	{ name = "Africa", texture = "6AFRICA", model = "6africa", id = 6 , price = 150 ,modded=false},
	{ name = "Cross", texture = "7CROSS", model = "7cross", id = 7 , price = 642 ,modded=false},
	{ name = "Cross2", texture = "7CROSS2", model = "7cross2", id = 7 , price = 358 ,modded=false},
	{ name = "Cross3", texture = "7CROSS3", model = "7cross3", id = 7 , price = 843 ,modded=false},
	{ name = "Mary", texture = "7MARY", model = "7mary", id = 7 , price = 900 ,modded=false},
	{ name = "SA", texture = "8SA", model = "8sa", id = 8 , price = 697 ,modded=false},
	{ name = "SA2", texture = "8SA2", model = "8sa2", id = 8 , price = 800 ,modded=false},
	{ name = "SA3", texture = "8SA3", model = "8sa3", id = 8 , price = 343 ,modded=false},
	{ name = "Santos", texture = "8SANTOS", model = "8santos", id = 8 , price = 150 ,modded=false},
	{ name = "Poker", texture = "8POKER", model = "8poker", id = 8 , price = 387 ,modded=false},
	{ name = "Gun", texture = "8GUN", model = "8gun", id = 8 , price = 1300 ,modded=false},
	{ name = "Crown", texture = "9CROWN", model = "9crown", id = 9 , price = 500 ,modded=false},
	{ name = "Gun", texture = "9GUN", model = "9gun", id = 9 , price = 700 ,modded=false},
	{ name = "Gun2", texture = "9GUN2", model = "9gun2", id = 9 , price = 120 ,modded=false},
	{ name = "Rasta", texture = "9RASTA", model = "9RASTA", id = 9 , price = 800 ,modded=false},
	{ name = "LS", texture = "10LS", model = "10ls", id = 10 , price = 970 ,modded=false},
	{ name = "LS2", texture = "10LS2", model = "10ls2", id = 10 , price = 456 ,modded=false},
	{ name = "LS3", texture = "10LS3", model = "10ls3", id = 10 , price = 230 ,modded=false},
	{ name = "LS4", texture = "10LS4", model = "10ls4", id = 10 , price = 800 ,modded=false},
	{ name = "LS5", texture = "10LS5", model = "10ls5", id = 10 , price = 1000 ,modded=false},
	{ name = "OG", texture = "10OG", model = "10og", id = 10 , price = 685 ,modded=false},
	{ name = "Weed", texture = "10WEED", model = "10weed", id = 10 , price = 700 ,modded=false},
	{ name = "Grove", texture = "11GROVE", model = "11grove", id = 11 , price = 654 ,modded=false},
	{ name = "Dice", texture = "11DICE", model = "11dice", id = 11 , price = 900 ,modded=false},
	{ name = "Dice2", texture = "11DICE2", model = "11dice2", id = 11 , price = 100 ,modded=false},
	{ name = "Jail Sign", texture = "11JAIL", model = "11jail", id = 11 , price = 870 ,modded=false},
}
